import { ListenerProfile } from '@/types';

export const MOCK_LISTENERS: ListenerProfile[] = [
  {
    id: 'mock-1',
    display_name: 'Priya M.',
    status: 'approved',
    bio: 'I went through a difficult breakup and learned that healing takes time. I am here to listen without judgment.',
    languages: ['English', 'Hindi'],
    tags: ['Breakup', 'Relationship', 'Loneliness'],
    rate_per_min_chat: 5,
    rate_per_min_call: 8,
    rate_per_min_video: 12,
    is_online: true,
    rating: 4.8,
    rating_count: 124,
    today_minutes: 45,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-2',
    display_name: 'Arjun K.',
    status: 'approved',
    bio: 'Career transitions can feel overwhelming. I have navigated job loss and found my path — happy to share that journey.',
    languages: ['English', 'Tamil'],
    tags: ['Career', 'Anxiety', 'Work stress'],
    rate_per_min_chat: 6,
    rate_per_min_call: 9,
    rate_per_min_video: 14,
    is_online: true,
    rating: 4.6,
    rating_count: 89,
    today_minutes: 72,
    daily_target_minutes: 120,
    gender: 'Male',
    avatar_url:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-3',
    display_name: 'Meera S.',
    status: 'approved',
    bio: 'Family conflicts are hard. I grew up in a complex household and understand how lonely it can feel.',
    languages: ['English', 'Hindi', 'Marathi'],
    tags: ['Family', 'Anxiety', 'Self-esteem'],
    rate_per_min_chat: 5,
    rate_per_min_call: 7,
    rate_per_min_video: 11,
    is_online: false,
    rating: 4.9,
    rating_count: 201,
    today_minutes: 30,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1438761681033-6461fadead4d?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-4',
    display_name: 'Rahul D.',
    status: 'approved',
    bio: 'Anxiety used to control my life. Through mindfulness and support, I learned to manage it. Here to help you too.',
    languages: ['English', 'Hindi', 'Bengali'],
    tags: ['Anxiety', 'Loneliness', 'Self-esteem'],
    rate_per_min_chat: 4,
    rate_per_min_call: 7,
    rate_per_min_video: 10,
    is_online: true,
    rating: 4.7,
    rating_count: 156,
    today_minutes: 90,
    daily_target_minutes: 120,
    gender: 'Male',
    avatar_url:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-5',
    display_name: 'Ananya R.',
    status: 'approved',
    bio: 'Heartbreak changed how I see myself. If you are struggling after a breakup, I am here to listen with empathy.',
    languages: ['English', 'Hindi'],
    tags: ['Breakup', 'Self-esteem', 'Loneliness'],
    rate_per_min_chat: 5,
    rate_per_min_call: 8,
    rate_per_min_video: 11,
    is_online: true,
    rating: 4.9,
    rating_count: 178,
    today_minutes: 55,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-6',
    display_name: 'Kavya P.',
    status: 'approved',
    bio: 'Loneliness can feel invisible. I have been there and know how much a kind conversation can help.',
    languages: ['English', 'Telugu'],
    tags: ['Loneliness', 'Anxiety', 'Relationship'],
    rate_per_min_chat: 4,
    rate_per_min_call: 7,
    rate_per_min_video: 10,
    is_online: true,
    rating: 4.5,
    rating_count: 92,
    today_minutes: 38,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-7',
    display_name: 'Sana I.',
    status: 'approved',
    bio: 'Relationships are complicated. I offer a calm space to talk through confusion without anyone taking sides.',
    languages: ['English', 'Hindi', 'Urdu'],
    tags: ['Relationship', 'Family', 'Breakup'],
    rate_per_min_chat: 6,
    rate_per_min_call: 9,
    rate_per_min_video: 13,
    is_online: true,
    rating: 4.8,
    rating_count: 143,
    today_minutes: 61,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e2?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-8',
    display_name: 'Divya N.',
    status: 'approved',
    bio: 'Work pressure and burnout are real. I left a toxic workplace and rebuilt my confidence — happy to share that path.',
    languages: ['English', 'Kannada'],
    tags: ['Career', 'Work stress', 'Anxiety'],
    rate_per_min_chat: 5,
    rate_per_min_call: 8,
    rate_per_min_video: 12,
    is_online: false,
    rating: 4.7,
    rating_count: 67,
    today_minutes: 22,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-9',
    display_name: 'Nisha T.',
    status: 'approved',
    bio: 'Grief does not follow a timeline. After losing someone close, I learned to carry pain with more gentleness.',
    languages: ['English', 'Tamil'],
    tags: ['Grief', 'Loneliness', 'Family'],
    rate_per_min_chat: 5,
    rate_per_min_call: 7,
    rate_per_min_video: 11,
    is_online: true,
    rating: 5.0,
    rating_count: 210,
    today_minutes: 48,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-10',
    display_name: 'Riya A.',
    status: 'approved',
    bio: 'Anxiety used to make everyday tasks feel impossible. Small steps and honest talk made a big difference for me.',
    languages: ['English', 'Hindi', 'Marathi'],
    tags: ['Anxiety', 'Self-esteem', 'Career'],
    rate_per_min_chat: 4,
    rate_per_min_call: 6,
    rate_per_min_video: 9,
    is_online: true,
    rating: 4.6,
    rating_count: 115,
    today_minutes: 33,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-11',
    display_name: 'Vikram S.',
    status: 'approved',
    bio: 'Switching careers in my thirties was scary. I can listen if you are feeling stuck or unsure about your next move.',
    languages: ['English', 'Hindi'],
    tags: ['Career', 'Work stress', 'Anxiety'],
    rate_per_min_chat: 6,
    rate_per_min_call: 9,
    rate_per_min_video: 14,
    is_online: true,
    rating: 4.4,
    rating_count: 54,
    today_minutes: 40,
    daily_target_minutes: 120,
    gender: 'Male',
    avatar_url:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=240&h=240&fit=crop&crop=face',
  },
  {
    id: 'mock-12',
    display_name: 'Isha K.',
    status: 'approved',
    bio: 'Parenting while managing your own mental health is hard. I am a mom who gets it — no judgment, just support.',
    languages: ['English', 'Hindi', 'Gujarati'],
    tags: ['Parenting', 'Family', 'Anxiety'],
    rate_per_min_chat: 5,
    rate_per_min_call: 8,
    rate_per_min_video: 12,
    is_online: true,
    rating: 4.9,
    rating_count: 167,
    today_minutes: 52,
    daily_target_minutes: 120,
    gender: 'Female',
    avatar_url:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=240&h=240&fit=crop&crop=face',
  },
];
